highlighter: pygments
permalink:   date
markdown:    redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
url: http://garyrafferty.com
